"""Estado inicial completo del proyecto

Revision ID: 0cc9815005a8
Revises: 
Create Date: 2026-07-23 11:36:09.099044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc9815005a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('monto_sugerido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('es_mensualidad', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion_cobros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_recargo', sa.Enum('MONTO_FIJO', 'PORCENTAJE', 'POR_DIA', 'PORCENTAJE_MENSUAL', name='tiporecargo'), nullable=False),
    sa.Column('valor_recargo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dias_gracia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_institucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=150), nullable=False),
    sa.Column('nombre_periodo_singular', sa.String(length=40), nullable=False),
    sa.Column('nombre_periodo_plural', sa.String(length=40), nullable=False),
    sa.Column('nombre_programa_singular', sa.String(length=40), nullable=False),
    sa.Column('nombre_programa_plural', sa.String(length=40), nullable=False),
    sa.Column('programa_es_femenino', sa.Boolean(), nullable=False),
    sa.Column('max_periodos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes_estudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('clave_carrera', sa.String(length=10), nullable=False),
    sa.Column('anio_generacion', sa.Integer(), nullable=False),
    sa.Column('duracion_anios', sa.Integer(), nullable=True),
    sa.Column('monto_mensualidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave_carrera', 'anio_generacion', name='uq_plan_clave_anio')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('DIRECTIVO', 'ADMINISTRATIVO', 'CONTADOR', 'CAPTURADOR', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('alumnos',
    sa.Column('matricula_id', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_certificado_prepa', sa.Date(), nullable=False),
    sa.Column('id_plan_fk', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'ACTIVO', 'BAJA_TEMPORAL', 'BAJA_DEFINITIVA', 'EGRESADO', name='estatusalumno'), nullable=False),
    sa.Column('grupo_actual', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('telefono_movil', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('numero_identificacion', sa.String(length=30), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=5), nullable=True),
    sa.Column('domicilio_calle_numero', sa.String(length=200), nullable=True),
    sa.Column('domicilio_ciudad', sa.String(length=100), nullable=True),
    sa.Column('domicilio_cp', sa.String(length=10), nullable=True),
    sa.Column('domicilio_estado', sa.String(length=100), nullable=True),
    sa.Column('contacto_emergencia_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_emergencia_telefono', sa.String(length=20), nullable=True),
    sa.Column('contacto_emergencia_parentesco', sa.String(length=50), nullable=True),
    sa.Column('como_se_entero', sa.String(length=200), nullable=True),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', 'MIXTO', name='turnoalumno'), nullable=True),
    sa.Column('modalidad', sa.Enum('ESCOLARIZADO', 'SEMIESCOLARIZADO', 'DISTANCIA', name='modalidadestudio'), nullable=True),
    sa.Column('escuela_prepa', sa.String(length=200), nullable=True),
    sa.Column('alergias_condiciones', sa.Text(), nullable=True),
    sa.Column('telefono_tutor', sa.String(length=20), nullable=True),
    sa.Column('cuatrimestre_actual', sa.Integer(), nullable=False),
    sa.Column('documentacion_pendiente', sa.Text(), nullable=True),
    sa.Column('materias_adeudadas', sa.Text(), nullable=True),
    sa.Column('faltas_administrativas', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan_fk'], ['planes_estudio.id'], ),
    sa.PrimaryKeyConstraint('matricula_id')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_curp'), ['curp'], unique=True)

    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=True),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.Column('creditos', sa.Float(), nullable=True),
    sa.Column('id_plan_fk', sa.Integer(), nullable=False),
    sa.CheckConstraint('cuatrimestre > 0', name='ck_materia_cuatrimestre_positivo'),
    sa.ForeignKeyConstraint(['id_plan_fk'], ['planes_estudio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_plan_fk', 'nombre', 'cuatrimestre', name='uq_materia_por_plan')
    )
    op.create_table('becas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_descuento', sa.Enum('PORCENTAJE', 'MONTO_FIJO', name='tipodescuentobeca'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('periodo_escolar', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('otorgada_por_fk', sa.Integer(), nullable=True),
    sa.Column('fecha_otorgada', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.ForeignKeyConstraint(['otorgada_por_fk'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('id_materia_fk', sa.Integer(), nullable=False),
    sa.Column('calificacion_final', sa.Float(), nullable=False),
    sa.Column('periodo_escolar', sa.String(length=20), nullable=False),
    sa.Column('fecha_captura', sa.DateTime(), nullable=True),
    sa.Column('capturado_por', sa.String(length=100), nullable=True),
    sa.Column('numero_acta', sa.String(length=50), nullable=True),
    sa.CheckConstraint('calificacion_final >= 0 AND calificacion_final <= 10', name='ck_calificacion_rango_valido'),
    sa.ForeignKeyConstraint(['id_materia_fk'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_fk', 'id_materia_fk', 'periodo_escolar', name='uq_calificacion_alumno_materia_periodo')
    )
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('concepto_cobro_fk', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recargo_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recargo_congelado', sa.Boolean(), nullable=False),
    sa.Column('periodo_escolar', sa.String(length=20), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'CANCELADO', name='estatuscargo'), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('generado_por_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_cobro_fk'], ['conceptos_cobro.id'], ),
    sa.ForeignKeyConstraint(['generado_por_fk'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.Enum('COMPROBANTE_DOMICILIO', 'INE', 'CURP_DOC', 'ACTA_NACIMIENTO', 'CERTIFICADO_PREPA', 'FOTOGRAFIA', 'OTRO', name='tipodocumento'), nullable=False),
    sa.Column('nombre_archivo_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('id_materia_fk', sa.Integer(), nullable=False),
    sa.Column('periodo_escolar', sa.String(length=20), nullable=False),
    sa.Column('usuario_fk', sa.Integer(), nullable=True),
    sa.Column('calificacion_anterior', sa.Float(), nullable=True),
    sa.Column('calificacion_nueva', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia_fk'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.ForeignKeyConstraint(['usuario_fk'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_estatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('usuario_fk', sa.Integer(), nullable=True),
    sa.Column('estatus_anterior', sa.Enum('PENDIENTE', 'ACTIVO', 'BAJA_TEMPORAL', 'BAJA_DEFINITIVA', 'EGRESADO', name='estatusalumno'), nullable=True),
    sa.Column('estatus_nuevo', sa.Enum('PENDIENTE', 'ACTIVO', 'BAJA_TEMPORAL', 'BAJA_DEFINITIVA', 'EGRESADO', name='estatusalumno'), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.ForeignKeyConstraint(['usuario_fk'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_fk', sa.String(length=20), nullable=False),
    sa.Column('id_materia_fk', sa.Integer(), nullable=False),
    sa.Column('periodo_escolar', sa.String(length=20), nullable=False),
    sa.Column('grupo', sa.String(length=20), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia_fk'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['matricula_fk'], ['alumnos.matricula_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_fk', 'id_materia_fk', 'periodo_escolar', name='uq_inscripcion_alumno_materia_periodo')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_fk', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=True),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'DEPOSITO', 'OTRO', name='metodopago'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('capturado_por_fk', sa.Integer(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('fecha_anulacion', sa.DateTime(), nullable=True),
    sa.Column('anulado_por_fk', sa.Integer(), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['anulado_por_fk'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['capturado_por_fk'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cargo_fk'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('inscripciones_materia')
    op.drop_table('historial_estatus')
    op.drop_table('historial_calificaciones')
    op.drop_table('documentos_alumno')
    op.drop_table('cargos')
    op.drop_table('calificaciones')
    op.drop_table('becas')
    op.drop_table('materias')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_curp'))

    op.drop_table('alumnos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    op.drop_table('planes_estudio')
    op.drop_table('configuracion_institucion')
    op.drop_table('configuracion_cobros')
    op.drop_table('conceptos_cobro')
    # ### end Alembic commands ###
