"""Agrega monto_mensualidad, roles nuevos y recargo mensual

Revision ID: 16f8ac8ec6c2
Revises: 9d6eda8308fd
Create Date: 2026-07-16 08:10:44.180929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f8ac8ec6c2'
down_revision = '9d6eda8308fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_cobros', schema=None) as batch_op:
        batch_op.alter_column('tipo_recargo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('MONTO_FIJO', 'PORCENTAJE', 'POR_DIA', 'PORCENTAJE_MENSUAL', name='tiporecargo'),
               existing_nullable=False)

    with op.batch_alter_table('planes_estudio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_mensualidad', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes_estudio', schema=None) as batch_op:
        batch_op.drop_column('monto_mensualidad')

    with op.batch_alter_table('configuracion_cobros', schema=None) as batch_op:
        batch_op.alter_column('tipo_recargo',
               existing_type=sa.Enum('MONTO_FIJO', 'PORCENTAJE', 'POR_DIA', 'PORCENTAJE_MENSUAL', name='tiporecargo'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
