"""Agregar índices en FKs de rendimiento (H4)

Revision ID: a3ffe23d5c99
Revises: d30d01098fb9
Create Date: 2026-08-13 08:16:50.099876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ffe23d5c99'
down_revision = 'd30d01098fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_id_plan_fk'), ['id_plan_fk'], unique=False)

    with op.batch_alter_table('calificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calificaciones_id_materia_fk'), ['id_materia_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_calificaciones_matricula_fk'), ['matricula_fk'], unique=False)

    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cargos_estatus'), ['estatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_cargos_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_cargos_matricula_fk'), ['matricula_fk'], unique=False)

    with op.batch_alter_table('inscripciones_materia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripciones_materia_id_materia_fk'), ['id_materia_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscripciones_materia_matricula_fk'), ['matricula_fk'], unique=False)

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materias_id_plan_fk'), ['id_plan_fk'], unique=False)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_cargo_fk'), ['cargo_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_fecha_pago'), ['fecha_pago'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_fecha_pago'))
        batch_op.drop_index(batch_op.f('ix_pagos_cargo_fk'))

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materias_id_plan_fk'))

    with op.batch_alter_table('inscripciones_materia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripciones_materia_matricula_fk'))
        batch_op.drop_index(batch_op.f('ix_inscripciones_materia_id_materia_fk'))

    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cargos_matricula_fk'))
        batch_op.drop_index(batch_op.f('ix_cargos_fecha_vencimiento'))
        batch_op.drop_index(batch_op.f('ix_cargos_estatus'))

    with op.batch_alter_table('calificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calificaciones_matricula_fk'))
        batch_op.drop_index(batch_op.f('ix_calificaciones_id_materia_fk'))

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_id_plan_fk'))

    # ### end Alembic commands ###
