"""agrega tabla contadores_folio

Revision ID: d30d01098fb9
Revises: 0cc9815005a8
Create Date: 2026-07-25 12:44:14.967130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30d01098fb9'
down_revision = '0cc9815005a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contadores_folio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('ultimo_valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'anio', name='uq_contador_folio_tipo_anio')
    )
    # ### end Alembic commands ###

    # --- Poblar el contador leyendo las actas YA emitidas, por año ---
    # Esto NO lo genera Alembic solo (no es un cambio de esquema): sin
    # este bloque, la tabla nueva quedaría vacía y la primera vez que se
    # pida un folio de un año que YA tiene actas capturadas, empezaría a
    # contar desde 1 otra vez -- chocando con actas reales ya existentes.
    # Recorremos todas las actas, agrupamos por año, y sembramos cada
    # (tipo, año) con el consecutivo más alto ya usado. Si no hay ninguna
    # acta todavía, no se inserta ninguna fila -- eso es correcto:
    # siguiente_folio() crea la primera fila sola, en 0, la primera vez
    # que se pida un folio de un (tipo, año) nuevo.
    conn = op.get_bind()
    filas = conn.execute(
        sa.text("SELECT numero_acta FROM calificaciones WHERE numero_acta LIKE 'ACTA-%'")
    ).fetchall()

    maximos_por_anio = {}
    for (numero_acta,) in filas:
        try:
            _, anio_str, consecutivo_str = numero_acta.split('-')
            anio = int(anio_str)
            consecutivo = int(consecutivo_str)
        except (ValueError, AttributeError):
            continue  # numero_acta con formato viejo/inesperado: se ignora, no rompe la migración
        maximos_por_anio[anio] = max(maximos_por_anio.get(anio, 0), consecutivo)

    if maximos_por_anio:
        contadores_folio = sa.table(
            'contadores_folio',
            sa.column('tipo', sa.String),
            sa.column('anio', sa.Integer),
            sa.column('ultimo_valor', sa.Integer),
        )
        op.bulk_insert(contadores_folio, [
            {'tipo': 'ACTA', 'anio': anio, 'ultimo_valor': valor}
            for anio, valor in maximos_por_anio.items()
        ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contadores_folio')
    # ### end Alembic commands ###
